server:
  host: 0.0.0.0
  port: 4443
  options:
    connections:
      routes:
        cors:
          origin:
          - 'http://0.0.0.0:4200'
          - 'http://localhost:4200'
          - 'http://127.0.0.1:4200'
swag:
  info:
    title: My Movie Library
mongodb:
  host: 0.0.0.0
  port: 27017
  db: projetAngular